/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.JOptionPane;

/**
 *
 * @author xxzofxx
 */
public class ortografia extends javax.swing.JFrame {

    /**
     * Creates new form ortografia
     */
    public ortografia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        brazo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        abeja = new javax.swing.JTextField();
        vena = new javax.swing.JTextField();
        blusa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnVerificar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("Aprendiendo a escribir bien");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 29, -1, -1));

        jLabel2.setForeground(new java.awt.Color(51, 255, 255));
        jLabel2.setText("La V y la B. Completa Las siguientes palabras con la v o con la b");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 62, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("razo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 125, -1, -1));
        getContentPane().add(brazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 121, 33, -1));

        jLabel4.setForeground(new java.awt.Color(0, 255, 255));
        jLabel4.setText("ena");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 125, -1, -1));

        jLabel5.setText("A");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 125, -1, -1));

        jLabel6.setForeground(new java.awt.Color(51, 255, 255));
        jLabel6.setText("lusa");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 125, -1, -1));

        abeja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abejaActionPerformed(evt);
            }
        });
        getContentPane().add(abeja, new org.netbeans.lib.awtextra.AbsoluteConstraints(681, 121, 33, -1));

        vena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venaActionPerformed(evt);
            }
        });
        getContentPane().add(vena, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 121, 33, -1));

        blusa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blusaActionPerformed(evt);
            }
        });
        getContentPane().add(blusa, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 121, 33, -1));

        jLabel7.setForeground(new java.awt.Color(0, 255, 255));
        jLabel7.setText("eja");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 125, -1, -1));

        btnVerificar.setBackground(new java.awt.Color(255, 255, 0));
        btnVerificar.setText("Verificar");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 240, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("/home/xxzofxx/Descargas/bee(1).png")); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 102, 71, 59));

        jLabel9.setIcon(new javax.swing.ImageIcon("/home/xxzofxx/Descargas/brazo.png")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 100, -1, 55));

        jLabel10.setIcon(new javax.swing.ImageIcon("/home/xxzofxx/Descargas/blusa.png")); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 116, -1, 55));

        jLabel11.setIcon(new javax.swing.ImageIcon("/home/xxzofxx/Descargas/venas.png")); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 102, -1, 55));

        jLabel12.setIcon(new javax.swing.ImageIcon("/home/xxzofxx/Imágenes/72-720357_coraje-el-perro-cobarde-dibujo.jpeg")); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -90, 830, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void venaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_venaActionPerformed

    private void blusaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blusaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blusaActionPerformed

    private void abejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abejaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abejaActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed

        String rUno = this.brazo.getText();

        String rDos = this.vena.getText();

        String rTres = this.blusa.getText();

        String rCuatro = this.abeja.getText();

        if (rUno.equals("B")) {

            JOptionPane.showMessageDialog(null, "La primer palabra es correcta!");

        } else {

            JOptionPane.showMessageDialog(null, "La primer palabra es incorrecta!");
              this.brazo.setText(null);

        }

        if (rDos.equals("V")) {

            JOptionPane.showMessageDialog(null, "La Segunda palabra es correcta!");

        } else {

            JOptionPane.showMessageDialog(null, "La Segunda palabra es incorrecta!");
              this.vena.setText(null);

        }
        
        
         if (rTres.equals("B")) {

            JOptionPane.showMessageDialog(null, "La Tercer palabra es correcta!");

        } else {

            JOptionPane.showMessageDialog(null, "La Tercer palabra es incorrecta!");
              this.blusa.setText(null);

        }
         
         if (rCuatro.equals("B")) {

            JOptionPane.showMessageDialog(null, "La Cuarta palabra es correcta!");

        } else {

            JOptionPane.showMessageDialog(null, "La Cuarta palabra es incorrecta!");
            
            
            this.abeja.setText(null);

        }



    }//GEN-LAST:event_btnVerificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ortografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ortografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ortografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ortografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ortografia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField abeja;
    private javax.swing.JTextField blusa;
    private javax.swing.JTextField brazo;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField vena;
    // End of variables declaration//GEN-END:variables
}
